# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  # Path to the solution file relative to the root of the project.


  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    

    - name: install

      run: |
            brew install llvm@16

            brew install xmake
            brew install libtool automake

                  cd ~

                  git clone https://gitcode.net/mirrors/microsoft/vcpkg

                  cd vcpkg

                  sh bootstrap-vcpkg.sh

                  ~/vcpkg/vcpkg integrate install

                  ~/vcpkg/vcpkg integrate bash

                  
                   #cd ~
                 #  bash <(curl -fsSL https://xmake.io/shget.text)   
                 export LDFLAGS="-L/usr/local/opt/llvm/lib"

                 export CPPFLAGS="-I/usr/local/opt/llvm/include"
                 
                 echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile
                 
                 /usr/bin/clang --version
                 /usr/local/opt/llvm/bin/clang --version
                 /usr/local/share/vcpkg/vcpkg install cppunit:x64-osx

    - name: make test

      run: |
            cd check-if-it-is-a-good-array
      
      
            xmake f --toolchain=llvm --sdk=/usr/local/opt/llvm/ -y -v
            xmake build -v -y
            xmake run -v
           
