name: ktlint-dependencies

on:
  push:
    branches: [ "master" ]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - uses: actions/checkout@v3
     
      - run: wget https://github.com/pinterest/ktlint/releases/download/0.49.0/ktlint
      
      
      - name: ktlint
        
        run: java --add-opens=java.base/java.lang=ALL-UNNAMED -jar "./ktlint" -F
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: pr
        with:
          commit-message: "ktlint"
          title: ktlint
          body: >
           ktlint
          branch: ktlint-updates
          author: GitHub <noreply@github.com>
          delete-branch: true
      - name: Retrieve commit sha
        id: commit
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
    
